export const constants={
    POST_FETCH:'POST_FETCH',
    POST_STORE:'POST_STORE',
    // LOGIN_SUCCESS:'LOGIN_SUCCESS',
    // LOGOUT_REQUEST:'LOGOUT_REQUEST',
    ATTENDENCE_FETCH:'ATTENDENCE_FETCH',
    RESULT_FETCH:'RESULT_FETCH'
    // SCHEMES_FETCH:'SCHEMES_FETCH',
    // COMM_FETCH:'COMM_FETCH',
    // APP_FETCH:'APP_FETCH'

}