export const constants={
    POST_FETCH:'POST_FETCH',
    CRED_FETCH:'CRED_FETCH',
    POST_STORE:'POST_STORE',
    ATTENDENCE_FETCH:'ATTENDENCE_FETCH',
    RESULT_FETCH:'RESULT_FETCH',
    UPDATES_FETCH:'UPDATES_FETCH',
    POSTER_FETCH:'POSTER_FETCH',
    INSTRUCTOR_FETCH:'INSTRUCTOR_FETCH'
}